### PR TITLE
Minor helper refactor

### PR DESCRIPTION
**Pull request by jonasfj**
Hi Liav,

On this branch I:
- refactored the test helper setup
- Added `taskcluster.utils.fromNow('1 hour')` to taskcluster client
- Started using `PulseTestReceiver` exposed as `helper.receiver` to receive messages as a promise. For docs see: https://github.com/taskcluster/taskcluster-base/blob/f4bab11da99771b582ff2833cfe55f2081e054d2/testing.js#L16-L57

I think these things will make it a lot simpler... I also added two very minimalistic tests to see if providing environment variables works with docker-worker. See [docker-worker docs](http://docs.taskcluster.net/docker-worker/) for details on what can be specified in `task.payload`.

Anyways, let me know what you think of this... And we can merge it. After merging it (which includes your PR), we can work on adding more tests and improving existing tests to cover more features.

By the way, I'm going to remove `node_modules/` from `master` right now so we don't have to be annoyed by that anymore :)

### CODE REVIEW

**Comment by jonasfj** [comment]
@liavkoren Hey, just tell me if this crazy :)
And/or if you have suggestions for how we could make the test helpers smarter.

Getting the framework setup right is a good thing, before we write too many tests. Making the tests running in parallel seems like something we can do later though (I think they're all fairly isolated).

**Comment by jonasfj** [comment]
Oh, I should mention, after adding `npm-shrinkwrap.json` you need the following steps to add/upgrade a package.
1. Put it into `package.json`
2. `rm -rf npm-shrinkwrap.json node_modules/`
3. `npm install`
4. `npm shrinkwrap`

(Deleting `node_modules/` is be optional, but if you don't delete `npm-shrinkwrap.json` it'll overwrite dependencies in `package.json`).

**Comment by liavkoren** [comment]
Hi Jonas. I was looking at the PulseTestReceiver object. As part of understanding it, I wrote out the pattern you used in pseudo-code. This was helpful for me, perhaps it's useful for others, perhaps not:

A pattern for the PulseTestReceiver object is:
- set up suite-level test fixture, including initialize a new `PulseTestReceiver`
- within a test-case, setup test-level fixture. Once fixture is ready,
- call `receiver.listenFor(<name>, <Event>)` where name is unique for the test suite.
- The receiver is now initialized and ready to receive messages, so within the
  `receiver.listenFor(<name>, <Event>).then()` callback, define and return the actions 
  that will result in the message receiver is waiting for. 
-  within the `receiver.listenFor(<name>, <Event>).then(<callback>).then()` `return 
  receiver.waitFor(<name>)` to `waitFor` the message we want.
- The next `.then` method after `return waitFor` now hass access to the message and
  we can carry out our success/fail tests.

The one thing that strikes me as Odd about this pattern is the need to use waitFor -- we've already set up the receiver and have a chain of promises. It might just be my inexperience with Promises in general that makes it seem strange to me. 

---

https://github.com/taskcluster/taskcluster-base/blob/f4bab11da99771b582ff2833cfe55f2081e054d2/testing.js#L35

Should that be `return receiver.listenFor(<name>, <Event>)`? 

I've just pushed refactored HelloWorld tests, I'll start looking at the ArtifactCreated tests next. I think overall the testReceiver pattern is very nice and semantic.

**Comment by jonasfj** [comment]
> call receiver.listenFor(<name>, <Event>) where name is unique for the test suite.
> The name only has to be unique for the test case, not the entire test suite.

Anyways, your observations/bullet-points are spot on... :)

> The one thing that strikes me as Odd about this pattern is the need to use waitFor -- we've already set up the receiver and have a chain of promises.

The reason for `waitFor` (and the naming of messages we're waiting for) is that when we call `listenFor` there is actually two events of interest:
- Event (A): We have started listening and will pickup a message that is published after this events.
- Event (B): We receive a message that was published after (A) and matches our routing pattern.

During testing we first setup listening, then wait for listening to have started (Event A), then we do something that causes a message to be published and wait for the message to arrive (Event B).

Because of this mixing it's easier to just associate a name with the events instead of having two promises. In taskcluster-queue (I'm current refactoring) I used to have a `helper.listenFor` which worked as follows:

``` js
var msgHandle = helper.listenFor(<Event>);
return msgHandle.ready.then(function() {
   // Do something that causes message to be published
}).then(function() {
  return msgHandle.message;
}).then(function(message) {
  // Look at message
});
```

In the pattern above `msgHandle` had two properties, `ready` and `message` both are promises. The `msgHandle.ready` promise is resolved at event A, and the `msgHandle.message` property is resolved at event B.
This pattern quickly got message when you have a lot of these `msgHandles` for different messages... So instead I created the receiver which fort the above would like this:

``` js
return receiver.listenFor('my-handle', <Event>).then(function() {
   // Do something that causes message to be published
}).then(function() {
  return receiver.waitFor('my-handle');
}).then(function(message) {
  // Look at message
});
```

---

> https://github.com/taskcluster/taskcluster-base/blob/f4bab11da99771b582ff2833cfe55f2081e054d2/testing.js#L35
> Should that be return receiver.listenFor(<name>, <Event>)? 

You're right, there is definitely a missing `return` statement. I'll add to taskcluster-base. It's nice to have good comments like this.

> I've just pushed refactored HelloWorld tests, I'll start looking at the ArtifactCreated tests next.

I assume this in PR #3 I'll definitely take a look at it... I guess I'll have to land this PR before we can merge the other one right?...

> I think overall the testReceiver pattern is very nice and semantic. 

It does have a tiny bit of magic to it.. but I don't see a more elegant way to do... Creating `PulseListener` instances for everything is a lot of repeated code.
I do wish it was possible for `listenFor` to return a promise that gave a promise... Example:

``` js
return receiver.listenFor(<Event>).then(function(msgPromise) {
   // DO something that publishes message
  return msgPromise;
}).then(function(message) {
  // Look at message....
});
```

But it's not possible for `msgPromise` to be a promise. As a the promise returned by `listenFor` cannot resolve to a promise... if you return a promise from a promise the promise returned will be resolved... So we would never reach the `//DO Something...` place...

Anyways, that is the reasoning... if you're interested :)

**Pull request merged**
